"""initial_migration_create_reviews_table

Revision ID: 90268bccb850
Revises: 
Create Date: 2025-09-15 05:35:00.113048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90268bccb850'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_name', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reviews_created_at', 'reviews', ['created_at'], unique=False)
    op.create_index('idx_reviews_product_id', 'reviews', ['product_id'], unique=False)
    op.create_index('idx_reviews_user_id', 'reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reviews_user_id', table_name='reviews')
    op.drop_index('idx_reviews_product_id', table_name='reviews')
    op.drop_index('idx_reviews_created_at', table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
